### PR TITLE
fix(submodel overview card): fix skeleton for submodelsoverview card

### LINKED ISSUE #50: Skeleton for SubmodelsOverview Card is never shown.
# Current Behavior
Right now the SubmodelsOverviewCard gets passed an 'isLoadingSubmodels' parameter as a prop, which is always false. Therefore the Skeleton, which should be shown, when the submodel is loading is never shown

# Expected Behavior
The Skeleton should be visible while the Submodels are loaded.

### PR DESCRIPTION
**Pull request by Xmilofranke**
# Description

This fixes the skeleton in the submodel overview card

Fixes #50

## Type of change

Please delete options that are not relevant.

-   [ ] Minor change (non-breaking change, e.g. documentation adaption)
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)

# Checklist:

-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [ ] I have added tests that prove my fix or my feature works
-   [x] New and existing tests pass locally with my changes
-   [x] My changes contain no console logs

### CODE REVIEW

File: src/app/[locale]/viewer/[base64AasId]/page.tsx [hunk 1]
```diff
@@ -29,6 +29,7 @@ export default function Page() {
     const [productImage, setProductImage] = useState<string>();
     const [isLoadingAas, setIsLoadingAas] = useState(false);
     const [isLoadingSubmodels, setIsLoadingSubmodels] = useState(false);
```
Comment (GailMelanie) [inline src/app/[locale]/viewer/[base64AasId]/page.tsx:31]: No longer used, can be removed. Same for [hasImage, setHasImage].

**Review by JonathanXITASO — APPROVED** [review]

**Review by GailMelanie — APPROVED** [review]
